[tool.bumpversion]
current_version = "1.0.0"
commit = true
commit_args = ""
tag = true
tag_name = "v{new_version}"
tag_message = "Automatic version bump {current_version} -> {new_version}"
message = "[skip actions] Automatic version bump {current_version} -> {new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "images-manifest.yml"
search = "version: {current_version}"
replace = "version: {new_version}"